Replace sh with bash in systemd unit
Since zookeeper v3.4.6 zkEnv.sh uses bash as a shebag. Moreover
it contains operations with arrays which sh (dash) doesn't
support. Because of it systemd unit doesn't work and fails with
following errors:
/bin/sh: 81: /opt/zookeeper-3.4.11/bin/zkEnv.sh: Syntax error: "(" unexpected (expecting "fi")
Error: Could not find or load main class org.apache.zookeeper.server.quorum.QuorumPeerMain
This patch replaces sh with bash in sytemd unit thereby fixes
that problem.